# Generated by Django 5.2 on 2025-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_percentages_profile_energy_intuition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mbti_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
