# Generated by Django 5.2 on 2025-06-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('hero_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntroductionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mbti_quote', models.TextField(blank=True, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('pic1', models.URLField(blank=True, null=True)),
                ('quote1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('subheading1', models.CharField(blank=True, max_length=255, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('quote2', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('personality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='introduction_page', to='mbti_data.personalitytype')),
            ],
        ),
        migrations.CreateModel(
            name='RomanticRelationshipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote1', models.TextField(blank=True, null=True)),
                ('text1', models.TextField()),
                ('pic1', models.URLField(blank=True, null=True)),
                ('subheading1', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField()),
                ('quote2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField()),
                ('pic2', models.URLField(blank=True, null=True)),
                ('subheading2', models.CharField(blank=True, max_length=255, null=True)),
                ('text4', models.TextField()),
                ('quote3', models.TextField(blank=True, null=True)),
                ('text5', models.TextField()),
                ('personality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='romantic_relationship', to='mbti_data.personalitytype')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthWeaknessPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_name_strength', models.CharField(max_length=100)),
                ('pic_strength', models.URLField(blank=True, null=True)),
                ('strength1', models.CharField(blank=True, max_length=100, null=True)),
                ('strength1_description', models.TextField(blank=True, null=True)),
                ('strength2', models.CharField(blank=True, max_length=100, null=True)),
                ('strength2_description', models.TextField(blank=True, null=True)),
                ('strength3', models.CharField(blank=True, max_length=100, null=True)),
                ('strength3_description', models.TextField(blank=True, null=True)),
                ('strength4', models.CharField(blank=True, max_length=100, null=True)),
                ('strength4_description', models.TextField(blank=True, null=True)),
                ('strength5', models.CharField(blank=True, max_length=100, null=True)),
                ('strength5_description', models.TextField(blank=True, null=True)),
                ('strength6', models.CharField(blank=True, max_length=100, null=True)),
                ('strength6_description', models.TextField(blank=True, null=True)),
                ('strength7', models.CharField(blank=True, max_length=100, null=True)),
                ('strength7_description', models.TextField(blank=True, null=True)),
                ('strength8', models.CharField(blank=True, max_length=100, null=True)),
                ('strength8_description', models.TextField(blank=True, null=True)),
                ('strength9', models.CharField(blank=True, max_length=100, null=True)),
                ('strength9_description', models.TextField(blank=True, null=True)),
                ('strength10', models.CharField(blank=True, max_length=100, null=True)),
                ('strength10_description', models.TextField(blank=True, null=True)),
                ('mbti_name_weakness', models.CharField(max_length=100)),
                ('pic_weakness', models.URLField(blank=True, null=True)),
                ('weakness1', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness1_description', models.TextField(blank=True, null=True)),
                ('weakness2', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness2_description', models.TextField(blank=True, null=True)),
                ('weakness3', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness3_description', models.TextField(blank=True, null=True)),
                ('weakness4', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness4_description', models.TextField(blank=True, null=True)),
                ('weakness5', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness5_description', models.TextField(blank=True, null=True)),
                ('weakness6', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness6_description', models.TextField(blank=True, null=True)),
                ('weakness7', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness7_description', models.TextField(blank=True, null=True)),
                ('weakness8', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness8_description', models.TextField(blank=True, null=True)),
                ('weakness9', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness9_description', models.TextField(blank=True, null=True)),
                ('weakness10', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness10_description', models.TextField(blank=True, null=True)),
                ('personality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strength_weakness_page', to='mbti_data.personalitytype')),
            ],
        ),
    ]
