# Generated by Django 5.2 on 2025-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='romanticrelationshipsection',
            name='subheading3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='romanticrelationshipsection',
            name='text6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
