# Generated by Django 5.2 on 2025-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0002_romanticrelationshipsection_subheading3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='romanticrelationshipsection',
            name='quote4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='romanticrelationshipsection',
            name='text7',
            field=models.TextField(blank=True, null=True),
        ),
    ]
