# Generated by Django 5.2 on 2025-06-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0003_romanticrelationshipsection_quote4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romanticrelationshipsection',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='romanticrelationshipsection',
            name='text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='romanticrelationshipsection',
            name='text4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='romanticrelationshipsection',
            name='text5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FriendshipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote1', models.TextField(blank=True, null=True)),
                ('text1', models.TextField()),
                ('pic1', models.URLField(blank=True, null=True)),
                ('subheading1', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('quote2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('subheading2', models.CharField(blank=True, max_length=255, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('quote3', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True, null=True)),
                ('personality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='mbti_data.personalitytype')),
            ],
        ),
    ]
