# Generated by Django 5.2 on 2025-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0007_conclusionsection_workplacehabitssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitytype',
            name='aspect1',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Observant', 'Observant'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='aspect2',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Observant', 'Observant'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='aspect3',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Observant', 'Observant'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='aspect4',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Observant', 'Observant'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
    ]
