# Generated by Django 5.2 on 2025-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0008_personalitytype_aspect1_personalitytype_aspect2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionpage',
            name='quote3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='quote4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='subheading2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='subheading3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='text5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='text6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='text7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introductionpage',
            name='text8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalitytype',
            name='aspect1',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Sensing', 'Sensing'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalitytype',
            name='aspect2',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Sensing', 'Sensing'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalitytype',
            name='aspect3',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Sensing', 'Sensing'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalitytype',
            name='aspect4',
            field=models.CharField(blank=True, choices=[('Introverted', 'Introverted'), ('Extraverted', 'Extraverted'), ('Intuitive', 'Intuitive'), ('Sensing', 'Sensing'), ('Thinking', 'Thinking'), ('Feeling', 'Feeling'), ('Judging', 'Judging'), ('Prospecting', 'Prospecting')], max_length=20, null=True),
        ),
    ]
