# Generated by Django 5.2 on 2025-06-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0009_introductionpage_quote3_introductionpage_quote4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_options', to='mbti_data.careerpathsection')),
            ],
        ),
    ]
