# Generated by Django 5.2 on 2025-06-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0010_careeroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusionsection',
            name='quote1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conclusionsection',
            name='quote2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
