# Generated by Django 5.2 on 2025-07-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbti_data', '0011_conclusionsection_quote1_conclusionsection_quote2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConclusionSection',
        ),
    ]
