# Generated by Django 5.2 on 2025-06-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
